version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always

    environment:
      - MYSQL_ROOT_PASSWORD=dbpass2024
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=dbadmin
      - MYSQL_PASSWORD=dbpass2024

    volumes:
      - mysql:/var/lib/mysql

    ports:
      - '3306:3306'

volumes:
  mysql:
